### ISSUE TITLE
Plot does not scale back up after the axis scales down

### ISSUE THREAD

**Issue by bjoyce3** [rseng/rse-phenotype#11]
Suspected Usage/expected behavoir:
- Each group should have a total of 100% across all dimensions
- The plot axis automagically resizes as you scale down. That seems to reinforce the idea that everything should add to 100%

How to recreate:
- scale each group dot down to 20 or 30%
- try to scale back up to 40 or 50% and the line/dot will stop at the scaled down value

Possible fix:
- Good question really. Allow percentages to be input into boxes in key:value pairs for all groups/dimensions somewhere on the page?
- That seems kind of busy for a web app

![Screen Shot 2020-07-09 at 20 47 33 (2)](https://user-images.githubusercontent.com/11023317/87114493-981f7b80-c225-11ea-9edd-5ad762bab609.png)

**Comment by vsoch** [comment]
Transferred again! So I thought of a quick fix to not allow the auto-scaling, and it seemed to do the trick! I updated the PR. As for the values adding to 100 - is this absolutely necessary? I'd like to hear your thoughts. My thinking is that I can vary from 0 to 100 on a bunch of dimensions. For example, 80% of the work that I do is for open source, and maybe also 80% is for the academic community. I'm not sure that I could represent that limiting the values to sum to 100. Anyhoo, you should be able to test the same PR, #10, and it will address this issue too. And yes, I seriously can't go to sleep when I know there is something I can fix, ha!

**Comment by bjoyce3** [comment]
The 100% is my limited thinking. I assumed 100% is 1 FTE or 40 hours a week. I'm pretty sure we all work more than that; this issue evidence included! 

I assumed 100% because that's the traditional way that kind of figure works, but I'm totally in for letting folks put in more than 100%. My phenotype isn't limited to 100% because I spend a lot more hours outside "1.0 FTE" helping people and answering questions so that my team doesn't have to as much. 

![bjoyce3-rse-phenotype](https://user-images.githubusercontent.com/11023317/87118408-2ac51800-c230-11ea-867f-c36d1211a688.png)

**Comment by vsoch** [comment]
This is fixed with #10
