### ISSUE TITLE
TypeError appears to have broken the Generator?

### ISSUE THREAD

**Issue by mwoodbri** [rseng/rse-phenotype#12]
I see the following in my browser's developer console when loading https://rseng.github.io/rse-phenotype/:
```
TypeError: "this.values is null"
    generateDatasets https://rseng.github.io/rse-phenotype/rse-phenotype.js:104
    render https://rseng.github.io/rse-phenotype/rse-phenotype.js:195
    mounted https://rseng.github.io/rse-phenotype/rse-phenotype.js:46
    VueJS 7
    <anonymous> https://rseng.github.io/rse-phenotype/rse-phenotype.js:11
vue.js:1897:15
```
This seems to make the Generator unusable for me (macOS + Safari/Firefox/Chrome). Reverting [this change](https://github.com/rseng/rse-phenotype/commit/43573770f128abd4678269e71d0a174b6fa5c86c#diff-fa27e3479958b524a6f0f931d8b47c3cL104
) appears to fix it.

**Comment by vsoch** [comment]
That indeed is weird, the fix was working locally (and doesn't seem to be now). Could you try again now?

**Comment by mwoodbri** [comment]
What a super-speedy response! Working great now - I'll go ahead and link to you from our newsletter as originally planned :) 

For reference: e381ff5. Many thanks.

**Comment by vsoch** [comment]
Awesome, thanks! And sorry about the bug!

**Comment by mwoodbri** [comment]
No worries. Should have said that this was all motivated by the thought that an RSE Phenotype is a prime candidate for inclusion in one's [GitHub profile](https://dev.to/m0nica/how-to-create-a-github-profile-readme-1paj)!
