### ISSUE TITLE
Issue that needs reproducing: multiple points

### ISSUE THREAD

**Issue by vsoch** [rseng/rse-phenotype#13]
If we look at http://us-rse.org/rse-stories/assets/img/phenotypes/cferenba-rse-phenotype-1.png we see that the "Software Engineering" Dimension has two values, one around 30 and the other around 100. It might be that the dimensions leave points to drag when a 5th is removed, or that adding a new dimension does not add a point to drag. In order to debug this, we will need the actual steps to reproduce. @exoticDFT

I've added the Hacktoberfest tabel to this issue, if addressed via a PR it will be given credit for a Hacktoberfest point.

**Comment by braingram** [comment]
I was able to reproduce this by loading the page and deleting one of the dimensions. This left a 5th point on the graph. Also, adding a dimension produces a graph with a missing point on the last line. Checking if the length of values is unequal to the length of the labels (dimensions) in genData can identify the problem and resetting the values appears to fix the issue.

**Comment by vsoch** [comment]
Closed with https://github.com/rseng/rse-phenotype/pull/14. Thank you @braingram !
