### ISSUE TITLE
It doesn't let me change the shape of phenotype

### ISSUE THREAD

**Issue by soichih** [rseng/rse-phenotype#4]
I am not sure if I am understanding how it works, but everytime I try to change the number of 1 axis, it resets one of the other axis to 0 (or close to 0) so I can't draw the shape that I'd like. I'd like to draw a shape so that sum of all axis will be equal to 100%..  How can I do that? 

My phenotype would be something like this..

Frontend Development 30%
Backend Development 35%
Documentation / Web development 5%
User support / Troubleshooting 20%
Misc. 10%

**Comment by vsoch** [comment]
You basically just define the axis first (all of them) in the box, so you would do:

Frontend Development, Backend Development, Documentation / Web Development, User Support / Troubleshooting, Misc

(note they are separated by commas). After the axis are drawn, then drag and drop to change the values. Does that make sense?

**Comment by soichih** [comment]
I think this issue happens if I have only 1 group listed?

Also, what is the unit for each axis? I thought it's a percentage, but maybe not?

**Comment by vsoch** [comment]
You need to write all of the groups before you edit the plot - the entire structure updates dynamically, so  yes, if you add one (and then try to customize) it's not going to work. If you only have one dimension (I hope not?) the plot type isn't appropriate.

It starts with all maxes at 100 (it can be 100% or 100 points, whatever you want) and then will adjust to be smaller to fit what you drag it to.

**Comment by vsoch** [comment]
I'm not a front end developer, so feel free to PR if you think it can be improved.

**Comment by vsoch** [comment]
@soichih have I clarified this for you?
