### ISSUE TITLE
Broken link: share your phenotype 

### ISSUE THREAD

**Issue by damianooldoni** [rseng/rse-phenotype#7]
The link "SHARE YOU PHENOTYPE" sends the user to an empty page. Only exporting via png possible.

**Comment by vsoch** [comment]
Thank you! Yes the link was updated but my permissions removed from my own repo [here](https://github.com/USRSE/rse-phenotypes) so I can't update or move it as I need to. I'll make noise about this again to see if I can recover my own code.

**Comment by vsoch** [comment]
Thanks for reporting this! I was able to transfer the repository, and then update the links. I tested and it works to link to the repository, so I'm going to close the issue. Thank you @damianooldoni !
